### ISSUE TITLE
we need some better way to talk then github issues

### ISSUE THREAD

**Issue by agrecascino** [agrecascino/Thestoryofnukingjapan#12]
i mean seriously

**Comment by redcrew3** [comment]
any good ways that you can think of? I can only think of steam or an IRC

**Comment by agrecascino** [comment]
both work for me

**Comment by agrecascino** [comment]
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
        "http://www.w3.org/TR/html4/strict.dtd">
<HTML>
<HEAD>
<TITLE>My website's main page</TITLE>
<style type="text/css">

</style>
</HEAD>
<BODY BGCOLOR="00FFCC">
  <center>
  <H1>Add me on steam : Everybody's hero > Interstellar</H1>
 
      
      <audio src="http://syphist.com/audio/spacejam.mp3" autoplay loop>        </audio>
    </h1>
  </center>
    <H1 class="style2 style3"></H1>
</BODY>
</HTML>

**Comment by redcrew3** [comment]
could you link me to your profile? I'm getting a bunch of different ones and I want to make sure I got the right one

**Comment by agrecascino** [comment]
http://steamcommunity.com/id/crecascino

**Comment by redcrew3** [comment]
added
