### ISSUE TITLE
implement s3m player

### ISSUE THREAD

**Issue by agrecascino** [agrecascino/Thestoryofnukingjapan#7]
eta : future
because music is nice.
some documentation is available here : http://bisqwit.iki.fi/jutut/kuvat/programming_examples/s3mplayer.pdf
keep in mind we can not use that due to it directly interfacing with a soundblaster sound card in dos.
bottom line- we can use this to help us

**Comment by agrecascino** [comment]
hey ill work on this tommorrow by the way

**Comment by redcrew3** [comment]
I will too. This is a fun little project. I'm coding with using the gcc so if we start implementing windows only code, I'll have to leave the testing and debugging to you. I'll still contribute where I can though.

**Comment by agrecascino** [comment]
we did it
